version: '2'
services:
  backend:
    build:
      context: ./backend
      args:
        - BASE_IMAGE=${BASE_IMAGE}
    environment:
      - ENV=${ENV}
    ports:
      - "${BACKEND_PORT}:5000"
      - "${DASHBOARD_PORT}:5555"
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - ./backend:/opt/pyor/backend:ro
      - data:/var/pyor
      - /tmp/pyor/log:/var/log/pyor
    links:
      - mongodb
      - rabbitmq
  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=${ENV}
      - BACKEND_URL=${BACKEND_URL}
      - DASHBOARD_URL=${DASHBOARD_URL}
    ports:
      - "${FRONTEND_PORT}:4200"
    depends_on:
      - backend
#    volumes:
#      - ./frontend:/usr/src/app
    links:
      - backend
  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
     - rabbitmq_data:/var/lib/rabbitmq
    environment:
     - RABBITMQ_DEFAULT_USER=pyor
     - RABBITMQ_DEFAULT_PASS=pyor
     - RABBITMQ_DEFAULT_VHOST=pyor
volumes:
  data:
  mongo_data:
  rabbitmq_data:
