version: '2'
services:
  backend:
    build:
      context: ./backend
      args:
        - BASE_IMAGE=${BASE_IMAGE}
    environment:
      - ENV=${ENV}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    ports:
      - "${BACKEND_PORT}:5000"
      - "${DASHBOARD_PORT}:5555"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/opt/mreq/backend:ro
      - data:/var/mreq
    links:
      - mongodb
      - redis
    env_file:
      - prod.env
  frontend:
    image: node:8
    environment:
      - NODE_ENV=${ENV}
      - BACKEND_URL=${BACKEND_URL}
      - DASHBOARD_URL=${DASHBOARD_URL}
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "${FRONTEND_PORT}:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    links:
      - backend
  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
volumes:
  data:
  mongo_data:
  redis_data: