version: '2'
services:
  backend:
    image: pyor/backend
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DBNAME=${MONGO_DBNAME}
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:5000"
      - "${DASHBOARD_PORT}:5555"
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - data:/var/pyor
    links:
      - mongodb
      - rabbitmq
  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
     - rabbitmq_data:/var/lib/rabbitmq
    environment:
     - RABBITMQ_DEFAULT_USER=pyor
     - RABBITMQ_DEFAULT_PASS=pyor
     - RABBITMQ_DEFAULT_VHOST=pyor
volumes:
  data:
  mongo_data:
  rabbitmq_data:
