name: pyor
channels:
- defaults
- r
dependencies:
# Base
- python=3.6.3
- pip
# Backend
- flask-cors=3.0.3
- ujson==1.35
# Workers
## Python
- pandas=0.20.3
- matplotlib=2.1.0
- scipy=0.19.1
- seaborn=0.8.0
- scikit-learn=0.19.1
- scikit-image=0.13.0
- statsmodels=0.8.0
- bokeh=0.12.10
- sqlalchemy=1.1.13
- numba=0.35.0
- numexpr=2.6.2
- sympy=1.1.1
- patsy=0.4.1
- h5py=2.7.0
- beautifulsoup4=4.6.0
- protobuf=3.4.0
- xlrd=1.1.0
- cloudpickle=0.4.0
- dill=0.2.5
- tensorflow=1.3.0
## R
- rpy2=2.9.0
- r-base=3.4.2
- r-rmarkdown=1.6
- r-tidyverse=1.1.1
- r-data.table=1.10.4
- r-caret=6.0-77
- r-rcurl=1.95_4.8
- r-devtools=1.13.3
- r-irkernel=0.8.9
- r-shiny=1.0.5
- r-forecast=8.2
- r-rsqlite=2.0
- r-reshape2=1.4.2
- r-nycflights13=0.2.2
- r-crayon=1.3.4
- r-randomforest=4.6_12
- r-ggplot2=2.2.1
- r-tensorflow=1.4
- pip:
  # Backend
  - celery==4.1.0
  - flower==0.9.1
  - mongoengine==0.14.3
  - blinker==1.4
  - eve==0.7.4
  - eve-swagger==0.0.8
  - flask-script==2.0.6
  # Workers