name: pyor
channels:
- defaults
dependencies:
# Base
- python=3.6.2
- pip
# Backend
- flask=0.12.2
- flask-cors=3.0.3
- rpy2=2.8.6
- werkzeug=0.12.2
# Workers
## Python
- anaconda
## R
- r-base=3.4.1
- r-rmarkdown=1.6
- r-tidyverse=1.1.1
- r-data.table=1.10.4-3
- r-caret=6.0-77
- r-rcurl=3.0
- r-devtools=1.13.3
- r-irkernel=0.7*
- r-shiny=0.14*
- r-forecast=7.3*
- r-rsqlite=1.1*
- r-reshape2=1.4*
- r-nycflights13=0.2*
- r-crayon=1.3*
- r-randomforest=4.6*
- pip:
  # Backend
  - celery==4.1.0
  - flower==0.9.2
  - mongoengine==0.14.3
  - blinker==1.4
  - eve==0.7.4
  - eve-swagger==0.0.8
  - flask-script==2.0.5
  - ujson==1.33
  # Workers
  - tensorflow==1.3.0
  - tensorflow-tensorboard==0.1.4