name: mreq
channels:
- defaults
dependencies:
- bzip2=1.0.6=3
- cairo=1.14.8=0
- click=6.7=py36_0
- curl=7.54.1=0
- flask=0.12.2=py36_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gsl=2.2.1=0
- harfbuzz=0.9.39=2
- icu=54.1=0
- itsdangerous=0.24=py36_0
- jbig=2.1=0
- jinja2=2.9.6=py36_0
- jpeg=9b=0
- krb5=1.13.2=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libiconv=1.14=0
- libpng=1.6.27=0
- libssh2=1.8.0=0
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- markupsafe=0.23=py36_2
- ncurses=5.9=10
- openssl=1.0.2l=0
- pango=1.40.3=1
- pcre=8.39=1
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- python=3.6.2=0
- r-base=3.4.1=0
- readline=6.2=2
- rpy2=2.8.6=py36r3.4.1_2
- setuptools=27.2.0=py36_0
- singledispatch=3.4.0.3=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.12.2=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - flask-script==2.0.5
  - future==0.16.0
  - gevent==1.2.2
  - greenlet==0.4.12
  - hiredis==0.2.0
  - mrq==0.2.1
  - objgraph==1.8.1
  - psutil==1.2.1
  - pymongo==3.5.0
  - redis==2.10.5
  - termcolor==1.1.0
  - ujson==1.33

