name: pyor
channels:
- defaults
dependencies:
# Base
- python=3.6.2
- pip
# Backend
- flask=0.12.2
- flask-cors=3.0.3
- rpy2=2.8.6
- werkzeug=0.12.2
# Workers
- anaconda
- r-base=3.4.1
- pip:
  # Backend
  - celery==4.1.0
  - flower==0.9.2
  - mongoengine==0.14.3
  - flask-script==2.0.5
  - ujson==1.33
  # Workers
  - tensorflow==1.3.0
  - tensorflow-tensorboard==0.1.4